version: '3'
services:
  
  nginxreverse:
    container_name: nginxreverse
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/conf.d:/etc/nginx/conf.d
      - ./conf/certs:/etc/ssl/private/
      - ./conf/nginx.conf:/etc/nginx/nginx.conf

  app1:
    container_name: app1
    image: nginx
    volumes:
      - ./app1.html:/usr/share/nginx/html/index.html
  app2:
    container_name: app2
    image: nginx
    volumes:
      - ./app2.html:/usr/share/nginx/html/index.html      
